---
ID: "980f4b06-bf0e-43b2-b40e-f02a9b84797c"
Parent: "2b9add3d-ef00-4acd-b7b4-fd99797c0a95"
Template: "2b9add3d-ef00-4acd-b7b4-fd99797c0a95"
Path: /sitecore/templates/Feature/ContentComponents/Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210306T145014Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5c87ea76-9308-4add-b42f-18c8049bd025"
      Hint: Style
      Value: Style1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6e09ce12-f8ec-4bdc-a0e4-976fa54824fb"
      Hint: Author
      Value: Anonymous Sitecoreholics
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa80d6ef-8e51-4012-af13-35e191216d3b"
    - ID: "8f302545-a18c-49ff-aa5b-009a63c76de8"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210306T145138Z
    - ID: "edde273a-a012-4501-803e-b1d82234c6c4"
      Hint: NavigationLinkText
      Value: Read more
